### ISSUE TITLE
플레이어 참여

### ISSUE THREAD

**Issue by peacecheejecake** [kb-3-team/dice-game#4]
## Description
참여를 원하는 플레이어가 선착순으로 입장합니다. 최대 3명의 플레이어가 입장하며, 항상 1명의 컴퓨터 플레이어도 참여합니다.

## Tasks
- [ ] 참여하는 플레이어 등록 
- [ ] 플레이어가 3명이 되면 새로운 플레이어 제한
- [ ] 컴퓨터 플레이어 기능
