### ISSUE TITLE
Roll 시 1이 나오면 해당 턴에서 획득한 모든 점수는 박탈, 턴 종료

### ISSUE THREAD

**Issue by Lee-JeongMin** [kb-3-team/dice-game#7]
## Description
Roll 시 1이 나오면 해당 턴에서 획득한 모든 점수는 박탈, 턴 종료

## Tasks
- [ ] 주사위가 1임을 판단
- [ ] 플레이어의 해당 턴의 점수 0점으로 등록
- [ ] 다음 플레이어가 누구인지 판단
